declare const styles: {
  readonly composerDock: string;
  readonly composer: string;
  readonly composerMeta: string;
  readonly fileInput: string;
  readonly composerGhost: string;
  readonly composerTerminal: string;
  readonly composerActionSpacer: string;
  readonly recordingStage: string;
  readonly recordingStatus: string;
  readonly recordingBars: string;
  readonly recordingBar: string;
  readonly recordingA11y: string;
  readonly processingSpinner: string;
  readonly recordCancel: string;
  readonly recordingFooter: string;
  readonly recordingActions: string;
  readonly recordStop: string;
  readonly voiceTriggerWrap: string;
  readonly voiceTooltip: string;
  readonly attachStrip: string;
  readonly attachChip: string;
  readonly attachThumb: string;
  readonly attachIcon: string;
  readonly attachName: string;
  readonly attachMeta: string;
  readonly attachNote: string;
  readonly attachRemove: string;
  readonly dropOverlay: string;
  readonly dropOverlayCard: string;
  readonly toolsWrap: string;
  readonly toolsMenu: string;
  readonly toolsMenuItem: string;
  readonly toolsMenuCopy: string;
};

export default styles;
